# Generated by Django 4.0.3 on 2022-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVLastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='EV static data last updated', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='RoutesLastUpdated',
        ),
        migrations.DeleteModel(
            name='StopLastUpdated',
        ),
        migrations.DeleteModel(
            name='StopTimeLastUpdated',
        ),
        migrations.DeleteModel(
            name='TripsLastUpdated',
        ),
    ]
