# Generated by Django 2.1.2 on 2018-10-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0002_policy_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutesLastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='routes last updated', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StopLastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Stop last updated', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StopTimeLastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='stop time last updated', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TripsLastUpdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Trips last updated', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
