# Generated by Django 2.1.2 on 2018-10-28 19:04

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0003_routeslastupdated_stoplastupdated_stoptimelastupdated_tripslastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
