# Generated by Django 2.1.2 on 2018-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0004_terms_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
