# Generated by Django 2.1.2 on 2018-10-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0005_downloaddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaddata',
            name='dataDownloaded',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
