# Generated by Django 2.1.2 on 2018-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactusform', '0008_auto_20181108_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
