# Generated by Django 2.1.2 on 2022-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('charger_type', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('open', models.CharField(blank=True, max_length=100, null=True)),
                ('close', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('staff', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_modes', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_numbers', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
