# Generated by Django 3.2.15 on 2022-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evlocations',
            name='station_type',
            field=models.CharField(default='charging', max_length=50),
        ),
    ]
