# Generated by Django 4.0.3 on 2022-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0004_rename_logo_url_evlocations_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evlocations',
            name='charger_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evlocations',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
