# Generated by Django 4.0.3 on 2022-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0006_alter_evlocations_contact_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evlocations',
            name='contact_numbers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
