# Generated by Django 4.0.3 on 2022-04-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0007_alter_evlocations_contact_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evlocations',
            name='charger_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evlocations',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
