# Generated by Django 4.0.3 on 2022-04-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0008_alter_evlocations_charger_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evlocations',
            name='cost_per_unit',
        ),
    ]
