# Generated by Django 4.0.3 on 2022-04-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0010_evlocations_dtl_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='evlocations',
            name='station_type',
            field=models.CharField(default='charging_station', max_length=50),
        ),
    ]
