# Generated by Django 4.0.3 on 2022-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0011_evlocations_station_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evlocations',
            name='station_type',
            field=models.CharField(default='charging', max_length=50),
        ),
    ]
