# Generated by Django 4.0.3 on 2022-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0012_alter_evlocations_station_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorMapping',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('vendor_connector_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mapped_connector_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
