# Generated by Django 4.0.3 on 2022-10-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0013_connectormapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectormapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
