# Generated by Django 4.0.3 on 2022-10-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0014_alter_connectormapping_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evlocations',
            old_name='station_type',
            new_name='station_types',
        ),
    ]
