# Generated by Django 4.0.3 on 2022-10-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0015_rename_station_type_evlocations_station_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evlocations',
            old_name='station_types',
            new_name='station_type',
        ),
    ]
