# Generated by Django 3.2.15 on 2022-11-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVUpdates', '0002_alter_evlocations_station_type'),
        ('EVUpdates', '0016_rename_station_types_evlocations_station_type'),
    ]

    operations = [
    ]
