# Generated by Django 4.0.3 on 2022-09-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerDataProvider', '0002_registerdataprovider_dtl_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdataprovider',
            name='approval_document',
            field=models.FileField(default='media/default.pdf', upload_to='media'),
        ),
        migrations.AddField(
            model_name='registerdataprovider',
            name='battery_swapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerdataprovider',
            name='charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerdataprovider',
            name='company_website',
            field=models.URLField(default='http://www.example.com'),
        ),
        migrations.AddField(
            model_name='registerdataprovider',
            name='operational_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
