# Generated by Django 4.0.3 on 2022-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerDataProvider', '0003_registerdataprovider_approval_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdataprovider',
            name='approval_document',
            field=models.FileField(default='media/default.pdf', upload_to=''),
        ),
    ]
