# Generated by Django 4.0.3 on 2022-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerDataProvider', '0004_alter_registerdataprovider_approval_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdataprovider',
            name='approval_document',
            field=models.FileField(default='media/default.pdf', upload_to='approval_documents'),
        ),
    ]
