# Generated by Django 4.0.3 on 2022-09-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerDataProvider', '0006_remove_registerdataprovider_approval_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdataprovider',
            old_name='authorisation_letter',
            new_name='authorisation_letters',
        ),
    ]
