# Generated by Django 4.0.3 on 2022-09-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerDataProvider', '0007_rename_authorisation_letter_registerdataprovider_authorisation_letters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdataprovider',
            old_name='authorisation_letters',
            new_name='authorisation_letter',
        ),
    ]
