# Generated by Django 2.1.2 on 2022-03-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloadRealDataForm', '0002_registerdataprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterDataProvider',
        ),
    ]
